In [35]:
import numpy as np
from scipy.linalg import solve

In [121]:
def gaussian(A,b):
    d = np.column_stack((A , b))
    d = d[d[:, 0].argsort()]
    d = d//d[0,0]
    Ae = d[0,:]
    A_aug = Ae
    for i in range(1, len(d)):
            e = d[i,:]-d[0,:]*d[i,0]
            Ae = np.vstack((Ae, e))
    m=len(d)
    x=2
    d = Ae[1:]
    z=1
    A_aug = np.vstack((A_aug, d[0,:]))
    Ae = A_aug
    while x <= m-1 and z < m-1:
        e = d[x-1,:]-d[0,:]*(d[x-1,z]/d[0,z])
        Ae = np.vstack((Ae, e))
        if x == m-1 and z < m-2:
            z+=1
            x=z
            d = Ae[x:]
            A_aug = np.vstack((A_aug, d[0,:]))
        else:
            if len(d)>2:
                x+=1
            else:
                x=m+1
    d = Ae[m-1:]
    A_aug = np.vstack((A_aug, d[-1,:]))
    return A_aug

In [122]:
A = np.arange(1, 17, dtype=np.float64).reshape(4,4)
A[1,2] = 88
A[1,3] = -3
A[2,3] = -3
print(f'A = {A}')
x = np.ones(A.shape[0])
print(f'Original x = {x}')
b = A @ x.T
print(f'Right hand side for testing: b = {b}')
Ae = gaussian(A, b)
print(f'Check if A was unchanged ')
print(f'Eliminated augmented matrix:\n {Ae}')
print(f'Eliminated augmented matrix A part: {Ae[:,:-1]}')
print(f'Eliminated augmented matrix b part: {Ae[:,Ae.shape[1]-1]}')
# Find solution
x = back(Ae[:,:-1],Ae[:,Ae.shape[1]-1])
print(f'Solution: {x}')

A = [[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
Original x = [1. 1. 1. 1.]
Right hand side for testing: b = [10. 96. 27. 58.]
Check if A was unchanged 
Eliminated augmented matrix:
 [[   1.     2.     3.     4.    10. ]
 [   0.    -4.    73.   -23.    46. ]
 [   0.     0.  -162.     7.  -155. ]
 [   0.     0.     0.    22.5   22.5]]
Eliminated augmented matrix A part: [[   1.     2.     3.     4. ]
 [   0.    -4.    73.   -23. ]
 [   0.     0.  -162.     7. ]
 [   0.     0.     0.    22.5]]
Eliminated augmented matrix b part: [  10.    46.  -155.    22.5]


NameError: name 'back' is not defined