In [57]:
pip install scipy.linalg

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement scipy.linalg (from versions: none)
ERROR: No matching distribution found for scipy.linalg
You should consider upgrading via the 'E:\Python 3-8-8\python.exe -m pip install --upgrade pip' command.


In [10]:
import numpy as np
from scipy.linalg import solve

In [14]:

# def FancyPrint(A, B, selected):
#     for row in range(len(B)):
#         print("(", end='')
#         for col in range(len(A[row])):
#              print("\t{1:10.2f}{0}".format(" " if (selected is None
# or selected != (row, col)) else "*", A[row][col]), end='')
#         print("\t) * (\tX{0}) = (\t{1:10.2f})".format(row + 1, B[row]))
# --- end of вывод системы на экран

# --- перемена местами двух строк системы
def SwapRows(A, B, row1, row2):
    A[row1], A[row2] = A[row2], A[row1]
    B[row1], B[row2] = B[row2], B[row1]
# --- end of перемена местами двух строк системы

# --- деление строки системы на число
def DivideRow(A, B, row, divider):
    A[row] = [a / divider for a in A[row]]
    B[row] /= divider
# --- end of деление строки системы на число

# --- сложение строки системы с другой строкой, умноженной на число
def CombineRows(A, B, row, source_row, weight):
    A[row] = [(a + k * weight) for a, k in zip(A[row], A[source_row])]
    B[row] += B[source_row] * weight
# --- end of сложение строки системы с другой строкой, умноженной начисло

# --- решение системы методом Гаусса (приведением к треугольному виду)
def Gauss(A, B):
    column = 0
    while (column < len(B)):
        # print("Ищем максимальный по модулю элемент в {0}-м столбце:".format(column + 1))
        current_row = None
        for r in range(column, len(A)):
            if current_row is None or abs(A[r][column]) > abs(A[current_row][column]):
                 current_row = r
        if current_row is None:
            # print("решений нет")
            return None
        # FancyPrint(A, B, (current_row, column))
        if current_row != column:
            # print("Переставляем строку с найденным элементом повыше:")
            SwapRows(A, B, current_row, column)
            # FancyPrint(A, B, (column, column))
        # print("Нормализуем строку с найденным элементом:")
        DivideRow(A, B, column, A[column][column])
        # FancyPrint(A, B, (column, column))
        print("Обрабатываем нижележащие строки:")
        for r in range(column + 1, len(A)):
            CombineRows(A, B, r, column, -A[r][column])
        FancyPrint(A, B, (column, column))
        column += 1
    print("Матрица приведена к треугольному виду, считаем решение")
    X = [0 for b in B]
    for i in range(len(B) - 1, -1, -1):
        X[i] = B[i] - sum(x * a for x, a in zip(X[(i + 1):], A[i][(i + 1):]))
    print("Получили ответ:")
    print("\n".join("X{0} =\t{1:10.2f}".format(i + 1, x) for i, x in
enumerate(X)))
    return X
# --- end of решение системы методом Гаусса (приведением к треугольному виду)
print("Исходная система:")
# FancyPrint(myA, myB, None)
print("Решаем:")


Исходная система:
Решаем:


In [15]:
A = [
    [1.,  2.,  3.,  4.,],
 [ 5.,  6., 88., -3.,],
 [ 9., 10., 11., -3.,],
 [13., 14., 15., 16.,],
 ]

B = [10., 96., 27., 58.,]
Gauss(A, B)

Обрабатываем нижележащие строки:
(	      1.00*	      1.08 	      1.15 	      1.23 	) * (	X1) = (	      4.46)
(	      0.00 	      0.62 	     82.23 	     -9.15 	) * (	X2) = (	     73.69)
(	      0.00 	      0.31 	      0.62 	    -14.08 	) * (	X3) = (	    -13.15)
(	      0.00 	      0.92 	      1.85 	      2.77 	) * (	X4) = (	      5.54)
Обрабатываем нижележащие строки:
(	      1.00 	      1.08 	      1.15 	      1.23 	) * (	X1) = (	      4.46)
(	      0.00 	      1.00*	      2.00 	      3.00 	) * (	X2) = (	      6.00)
(	      0.00 	      0.00 	      0.00 	    -15.00 	) * (	X3) = (	    -15.00)
(	      0.00 	      0.00 	     81.00 	    -11.00 	) * (	X4) = (	     70.00)
Обрабатываем нижележащие строки:
(	      1.00 	      1.08 	      1.15 	      1.23 	) * (	X1) = (	      4.46)
(	      0.00 	      1.00 	      2.00 	      3.00 	) * (	X2) = (	      6.00)
(	      0.00 	      0.00 	      1.00*	     -0.14 	) * (	X3) = (	      0.86)
(	      0.00 	      0.00 	      0.00 	    -15.00 	) * (	X4) = (	 

[1.0000000000000009, 0.9999999999999991, 1.0, 1.0000000000000002]

In [16]:
A = np.arange(1, 17, dtype=np.float64).reshape(4,4)
A[1,2] = 88
A[1,3] = -3
A[2,3] = -3
print(f'A = {A}')
x = np.ones(A.shape[0])
print(f'Original x = {x}')
B = A @ x.T
print(f'Right hand side for testing: b = {B}')
Ae = Gauss(A, B)
print(f'Check if A was unchanged ')
print(f'Eliminated augmented matrix:\n {Ae}')
print(f'Eliminated augmented matrix A part: {Ae[:,:-1]}')
print(f'Eliminated augmented matrix B part: {Ae[:,Ae.shape[1]-1]}')
# Find solution
x = back(Ae[:,:-1],Ae[:,Ae.shape[1]-1])
print(f'Solution: {x}')

A = [[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
Original x = [1. 1. 1. 1.]
Right hand side for testing: b = [10. 96. 27. 58.]
Обрабатываем нижележащие строки:
(	      1.00*	      2.00 	      3.00 	      4.00 	) * (	X1) = (	     58.00)
(	      0.00 	     -4.00 	     73.00 	    -23.00 	) * (	X2) = (	   -194.00)
(	      0.00 	     -8.00 	    -16.00 	    -39.00 	) * (	X3) = (	   -495.00)
(	      0.00 	      0.00 	      0.00 	      0.00 	) * (	X4) = (	    -48.00)
Обрабатываем нижележащие строки:
(	      1.00 	      2.00 	      3.00 	      4.00 	) * (	X1) = (	     58.00)
(	     -0.00 	      1.00*	    -18.25 	      5.75 	) * (	X2) = (	    123.75)
(	      0.00 	      0.00 	      0.00 	      0.00 	) * (	X3) = (	    301.00)
(	      0.00 	      0.00 	      0.00 	      0.00 	) * (	X4) = (	    -48.00)
Обрабатываем нижележащие строки:
(	      1.00 	      2.00 	      3.00 	      4.00 	) * (	X1) = (	     58.00)
(	     -0.00 	      1.00 	    -18.25 	      5.75 	) * (	X2

C:\Users\1B72~1\AppData\Local\Temp/ipykernel_8408/3819483968.py:18: RuntimeWarning: invalid value encountered in double_scalars
  A[row] = [a / divider for a in A[row]]
C:\Users\1B72~1\AppData\Local\Temp/ipykernel_8408/3819483968.py:19: RuntimeWarning: divide by zero encountered in double_scalars
  B[row] /= divider
C:\Users\1B72~1\AppData\Local\Temp/ipykernel_8408/3819483968.py:25: RuntimeWarning: invalid value encountered in double_scalars
  B[row] += B[source_row] * weight


TypeError: list indices must be integers or slices, not tuple

In [53]:
def gaussian(A,b):
    cout = 0                      # Определить время расчета
    m, n = A.shape # Количество строк и столбцов матрицы a
    if ( m < n ):
        print("«Есть пространство для решения».")# Убедитесь, что количество уравнений больше, чем количество неизвестных
    else:
        l = np.zeros((n,n))
    for i in range(n):
                            # фактор ограничения
        if (A[i][i] == 0):
            print("no answer")

                    # j означает столбец
        for k in range(n - 1):          # k представляет первый слой цикла,(0，n-1)Строка 
            for i in range(k + 1, n):      # i означает цикл второго слоя,(k+1,n)Строка,Рассчитать коэффициент исключения строки
                l[i][k] = A[i][k] / A[k][k]          #Calculationl
                cout += 1                              # Время расчета плюс один
                for j in range(m):            # j представляет столбец, выполнять операции с каждым столбцом
                    A[i][j] = A[i][j] - l[i][k] * A[k][j]
                    cout += 1
                    b[i] = b[i] - l[i][k] * b[k]
                    # Вернуться к решению уравнения
            x = np.zeros(n)                                              # Сначала установите значение отмены назначения равным нулю, а затем вычислите одно за другим
            x[n - 1] = b[n - 1] / A[n - 1][n - 1]  # Сначала вычислить последнее x решение

        for i in range(n - 2, -1, -1):            # Вернуть и пересчитать каждое решение по очереди
            for j in range(i + 1, n):
                b[i] -= A[i][j] * x[j]              # Поскольку увеличение и уменьшение
                x[i] = b[i] / A[i][i]
        for i in range(n):
            print("x" + str(i + 1) + " = ", x[i])
            print("x" " = ", x)
            print("«Расчеты»," "=", cout)
# return A_aug

In [54]:
a = np.arange(1, 17, dtype=np.float64).reshape(4,4)
a[1,2] = 88
a[1,3] = -3
a[2,3] = -3
print(type(a))
print(f'A = {a}')
x = np.ones(a.shape[0])
print(f'Original x = {x}')
b = a @ x.T
gaussian(a, b)

<class 'numpy.ndarray'>
A = [[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
Original x = [1. 1. 1. 1.]
x1 =  -488.83724279835377
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x2 =  456.66615226337444
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x3 =  -7.320576131687243
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x4 =  -98.13333333333334
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x1 =  -1681.51378600823
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x2 =  809.9462962962962
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x3 =  -11.56090534979424
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x4 =  -98.13333333333334
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x1 =  -3413.2576131687233
x =

In [ ]:
a = np.array([[0.5, 1.1, 3.1], [2.0, 4.5, 0.36], [5.0, 0.96, 6.5]])        # Матрица входных коэффициентов
b = np.array([-6.0, 0.020, 0.96])                                                                            # Расширенная матрица с одним столбцом
gaussian(a, b)

In [ ]:
def myGauss(m):
    # eliminate columns
    for col in range(len(m[0])):
        for row in range(col+1, len(m)):
            r = [(rowValue * (-(m[row][col] / m[col][col]))) for rowValue in m[col]]
            m[row] = [sum(pair) for pair in zip(m[row], r)]
    # now backsolve by substitution
    ans = []
    m.reverse() # makes it easier to backsolve
    for sol in range(len(m)):
            if sol == 0:
                ans.append(m[sol][-1] / m[sol][-2])
            else:
                inner = 0
                # substitute in all known coefficients
                for x in range(sol):
                    inner += (ans[x]*m[sol][-2-x])
                # the equation is now reduced to ax + b = c form
                # solve with (c - b) / a
                ans.append((m[sol][-1]-inner)/m[sol][-sol-2])
    ans.reverse()
    return ans

In [50]:
A = np.arange(1, 17, dtype=np.float64).reshape(4,4)
A[1,2] = 88
A[1,3] = -3
A[2,3] = -3
print(f'A = {A}')
x = np.ones(A.shape[0])
print(f'Original x = {x}')
b = A @ x.T
print(f'Right hand side for testing: b = {b}')
Ae = gaussian(A, b)
print(f'Check if A was unchanged ')
print(f'Eliminated augmented matrix:\n {Ae}')
print(f'Eliminated augmented matrix A part: {Ae[:,:-1]}')
print(f'Eliminated augmented matrix b part: {Ae[:,Ae.shape[1]-1]}')
# Find solution
x = back(Ae[:,:-1],Ae[:,Ae.shape[1]-1])
print(f'Solution: {x}')

A = [[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
Original x = [1. 1. 1. 1.]
Right hand side for testing: b = [10. 96. 27. 58.]
x1 =  -488.83724279835377
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x2 =  456.66615226337444
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x3 =  -7.320576131687243
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x4 =  -98.13333333333334
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x1 =  -1681.51378600823
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x2 =  809.9462962962962
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x3 =  -11.56090534979424
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x4 =  -98.13333333333334
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x1

TypeError: 'NoneType' object is not subscriptable

In [40]:
def make_identity(matrix):
    matrix = ([ 1,  2,  3,  4.]
    [ 5,  6, 88, -3.]
    [ 9, 10, 11, -3.]
    [13, 14, 15, 16.])
    # перебор строк в обратном порядке 
    for nrow in range(len(matrix)-1,0,-1):
        row = matrix[nrow]
        for upper_row in matrix[:nrow]:
            factor = upper_row[nrow]
            upper_row -= factor*row
    return matrix

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\1B72~1\AppData\Local\Temp/ipykernel_5608/1517465407.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  matrix = ([ 1,  2,  3,  4.]
