In [19]:
import numpy as np

In [49]:
def gaussian(A,b):
    cout = 0                      # Определить время расчета
    m, n = A.shape # Количество строк и столбцов матрицы a
    if ( m < n ):
        print("«Есть пространство для решения».")# Убедитесь, что количество уравнений больше, чем количество неизвестных
    else:
        l = np.zeros((n,n))
    for i in range(n):
                            # фактор ограничения
        if (A[i][i] == 0):
            print("no answer")

                    # j означает столбец
        for k in range(n - 1):          # k представляет первый слой цикла,(0，n-1)Строка 
            for i in range(k + 1, n):      # i означает цикл второго слоя,(k+1,n)Строка,Рассчитать коэффициент исключения строки
                l[i][k] = A[i][k] / A[k][k]          #Calculationl
                cout += 1                              # Время расчета плюс один
                for j in range(m):            # j представляет столбец, выполнять операции с каждым столбцом
                    A[i][j] = A[i][j] - l[i][k] * A[k][j]
                    cout += 1
                    b[i] = b[i] - l[i][k] * b[k]
                    # Вернуться к решению уравнения
            x = np.zeros(n)                                              # Сначала установите значение отмены назначения равным нулю, а затем вычислите одно за другим
            x[n - 1] = b[n - 1] / A[n - 1][n - 1]  # Сначала вычислить последнее x решение

        for i in range(n - 2, -1, -1):            # Вернуть и пересчитать каждое решение по очереди
            for j in range(i + 1, n):
                b[i] -= A[i][j] * x[j]              # Поскольку увеличение и уменьшение
                x[i] = b[i] / A[i][i]
        for i in range(n):
            print("x" + str(i + 1) + " = ", x[i])
            print("x" " = ", x)
            print("«Расчеты»," "=", cout)
# return A_aug

In [52]:
a = np.arange(1, 17, dtype=np.float64).reshape(4,4)
a[1,2] = 88
a[1,3] = -3
a[2,3] = -3
print(type(a))
print(f'A = {a}')
x = np.ones(a.shape[0])
print(f'Original x = {x}')
b = a @ x.T
gaussian(a, b)

<class 'numpy.ndarray'>
A = [[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
Original x = [1. 1. 1. 1.]
x1 =  -488.83724279835377
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x2 =  456.66615226337444
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x3 =  -7.320576131687243
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x4 =  -98.13333333333334
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x1 =  -1681.51378600823
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x2 =  809.9462962962962
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x3 =  -11.56090534979424
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x4 =  -98.13333333333334
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x1 =  -3413.2576131687233
x =

In [45]:
a = np.array([[0.5, 1.1, 3.1], [2.0, 4.5, 0.36], [5.0, 0.96, 6.5]])        # Матрица входных коэффициентов
b = np.array([-6.0, 0.020, 0.96])                                                                            # Расширенная матрица с одним столбцом
gaussian(a, b)

x1 =  0.0
x2 =  -1415.1452266896774
x3 =  -17.73542547084445
x =  [    0.         -1415.14522669   -17.73542547]
«Расчеты»,= 12
x1 =  3211.2791366365263
x2 =  -1415.1452266896774
x3 =  -17.73542547084445
x =  [ 3211.27913664 -1415.14522669   -17.73542547]
«Расчеты»,= 12
x1 =  0.0
x2 =  -3550.490453379357
x3 =  -17.73542547084445
x =  [    0.         -3550.49045338   -17.73542547]
«Расчеты»,= 24
x1 =  11132.317771990349
x2 =  -3550.490453379357
x3 =  -17.73542547084445
x =  [11132.31777199 -3550.49045338   -17.73542547]
«Расчеты»,= 24
x1 =  0.0
x2 =  -5685.835680069037
x3 =  -17.73542547084445
x =  [    0.         -5685.83568007   -17.73542547]
«Расчеты»,= 36
x1 =  23751.115906061466
x2 =  -5685.835680069037
x3 =  -17.73542547084445
x =  [ 2.37511159e+04 -5.68583568e+03 -1.77354255e+01]
«Расчеты»,= 36


In [50]:
A = np.arange(1, 17, dtype=np.float64).reshape(4,4)
A[1,2] = 88
A[1,3] = -3
A[2,3] = -3
print(f'A = {A}')
x = np.ones(A.shape[0])
print(f'Original x = {x}')
b = A @ x.T
print(f'Right hand side for testing: b = {b}')
Ae = gaussian(A, b)
print(f'Check if A was unchanged ')
print(f'Eliminated augmented matrix:\n {Ae}')
print(f'Eliminated augmented matrix A part: {Ae[:,:-1]}')
print(f'Eliminated augmented matrix b part: {Ae[:,Ae.shape[1]-1]}')
# Find solution
x = back(Ae[:,:-1],Ae[:,Ae.shape[1]-1])
print(f'Solution: {x}')

A = [[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
Original x = [1. 1. 1. 1.]
Right hand side for testing: b = [10. 96. 27. 58.]
x1 =  -488.83724279835377
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x2 =  456.66615226337444
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x3 =  -7.320576131687243
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x4 =  -98.13333333333334
x =  [-488.8372428   456.66615226   -7.32057613  -98.13333333]
«Расчеты»,= 30
x1 =  -1681.51378600823
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x2 =  809.9462962962962
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x3 =  -11.56090534979424
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x4 =  -98.13333333333334
x =  [-1681.51378601   809.9462963    -11.56090535   -98.13333333]
«Расчеты»,= 60
x1

TypeError: 'NoneType' object is not subscriptable

In [40]:
def make_identity(matrix):
    matrix = ([ 1,  2,  3,  4.]
    [ 5,  6, 88, -3.]
    [ 9, 10, 11, -3.]
    [13, 14, 15, 16.])
    # перебор строк в обратном порядке 
    for nrow in range(len(matrix)-1,0,-1):
        row = matrix[nrow]
        for upper_row in matrix[:nrow]:
            factor = upper_row[nrow]
            upper_row -= factor*row
    return matrix

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\1B72~1\AppData\Local\Temp/ipykernel_5608/1517465407.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  matrix = ([ 1,  2,  3,  4.]
