In [1]:
import numpy as np
from scipy.linalg import solve

ModuleNotFoundError: No module named 'scipy'

In [55]:
def FancyPrint(A, B, selected):
    for row in range(len(B)):
        print("(", end='')
        for col in range(len(A[row])):
             print("\t{1:10.2f}{0}".format(" " if (selected is None or selected != (row, col)) else "*", A[row][col]), end='')
        print("\t) * (\tX{0}) = (\t{1:10.2f})".format(row + 1, B[row]))
# --- end of вывод системы на экран

# --- перемена местами двух строк системы
def SwapRows(A, B, row1, row2):
    A[[row1, row2]] = A[[row2, row1]]
#     A[row1], A[row2] = A[row2], A[row1]
    B[[row1, row2]] = B[[row2, row1]]
#     return A, B
# --- end of перемена местами двух строк системы

# --- деление строки системы на число
def DivideRow(A, B, row, divider):
    A[row] = [a / divider for a in A[row]]
    B[row] /= divider
# --- end of деление строки системы на число

# --- сложение строки системы с другой строкой, умноженной на число
def CombineRows(A, B, row, source_row, weight):
    A[row] = [(a + k * weight) for a, k in zip(A[row], A[source_row])]
    B[row] += B[source_row] * weight
# --- end of сложение строки системы с другой строкой, умноженной начисло

# --- решение системы методом Гаусса (приведением к треугольному виду)
def Gauss(A, B):
    column = 0
    while (column < len(B)):
        print("Ищем максимальный по модулю элемент в {0}-м столбце:".format(column + 1))
        current_row = None
        for r in range(column, len(A)):
            if current_row is None or abs(A[r][column]) > abs(A[current_row][column]):
                 current_row = r
        if current_row is None:
            print("решений нет")
            return None
        FancyPrint(A, B, (current_row, column))
        if current_row != column:
            print("Переставляем строку с найденным элементом повыше:")
            SwapRows(A, B, current_row, column)
            FancyPrint(A, B, (column, column))
        print("Нормализуем строку с найденным элементом:")
        DivideRow(A, B, column, A[column][column])
        FancyPrint(A, B, (column, column))
        print("Обрабатываем нижележащие строки:")
        for r in range(column + 1, len(A)):
            CombineRows(A, B, r, column, -A[r][column])
        FancyPrint(A, B, (column, column))
        column += 1
    print("Матрица приведена к треугольному виду, считаем решение")
    X = [0 for b in B]
    for i in range(len(B) - 1, -1, -1):
        X[i] = B[i] - sum(x * a for x, a in zip(X[(i + 1):], A[i][(i + 1):]))
    print("Получили ответ:")
    print("\n".join("X{0} =\t{1:10.2f}".format(i + 1, x) for i, x in
enumerate(X)))
    return X

In [31]:
A = [
    [1.,  2.,  3.,  4.,],
 [ 5.,  6., 88., -3.,],
 [ 9., 10., 11., -3.,],
 [13., 14., 15., 16.,],
 ]
B = [10., 96., 27., 58.,]
print(A)
print(B)
# print(SwapRows(A,B,1,1))

[[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 88.0, -3.0], [9.0, 10.0, 11.0, -3.0], [13.0, 14.0, 15.0, 16.0]]
[10.0, 96.0, 27.0, 58.0]


In [36]:
out1, out2 = SwapRows(A,B,1,2)

In [37]:
print(out1)

[[1.0, 2.0, 3.0, 4.0], [9.0, 10.0, 11.0, -3.0], [5.0, 6.0, 88.0, -3.0], [13.0, 14.0, 15.0, 16.0]]


In [38]:
print(out2)

[10.0, 27.0, 96.0, 58.0]


In [51]:
A = np.arange(1, 17, dtype=np.float64).reshape(4,4)
A[1,2] = 88
A[1,3] = -3
A[2,3] = -3
print(f'A = {A}')
x = np.ones(A.shape[0])
print(f'Original x = {x}')
B = A @ x.T

A = [[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
Original x = [1. 1. 1. 1.]


In [52]:
print(A)
print(B)

[[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
[10. 96. 27. 58.]


In [53]:
B[[0, 1]] = B[[1, 0]]

In [54]:
B

array([96., 10., 27., 58.])

In [50]:
B

array([96., 96., 27., 58.])

In [46]:
A

array([[ 5.,  6., 88., -3.],
       [ 5.,  6., 88., -3.],
       [ 9., 10., 11., -3.],
       [13., 14., 15., 16.]])

In [41]:
out1, out2 = SwapRows(A,B,1,2)

In [42]:
print(out1)
print(out2)

[[ 1.  2.  3.  4.]
 [ 9. 10. 11. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
[10. 27. 96. 58.]


In [57]:
A = np.arange(1, 17, dtype=np.float64).reshape(4,4)
A[1,2] = 88
A[1,3] = -3
A[2,3] = -3
print(f'A = {A}')
x = np.ones(A.shape[0])
print(f'Original x = {x}')
B = A @ x.T
print(f'Right hand side for testing: B = {B}')
Ae = Gauss(A, B)
print(type(Ae))
print(f'Check if A was unchanged ')
print(f'Eliminated augmented matrix:\n {Ae}')
print(f'Eliminated augmented matrix A part: {Ae[:,:-1]}')
print(f'Eliminated augmented matrix B part: {Ae[:,Ae.shape[1]-1]}')
# Find solution
x = back(Ae[:,:-1],Ae[:,Ae.shape[1]-1])
print(f'Solution: {x}')

A = [[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
Original x = [1. 1. 1. 1.]
Right hand side for testing: B = [10. 96. 27. 58.]
Ищем максимальный по модулю элемент в 1-м столбце:
(	      1.00 	      2.00 	      3.00 	      4.00 	) * (	X1) = (	     10.00)
(	      5.00 	      6.00 	     88.00 	     -3.00 	) * (	X2) = (	     96.00)
(	      9.00 	     10.00 	     11.00 	     -3.00 	) * (	X3) = (	     27.00)
(	     13.00*	     14.00 	     15.00 	     16.00 	) * (	X4) = (	     58.00)
Переставляем строку с найденным элементом повыше:
(	     13.00*	     14.00 	     15.00 	     16.00 	) * (	X1) = (	     58.00)
(	      5.00 	      6.00 	     88.00 	     -3.00 	) * (	X2) = (	     96.00)
(	      9.00 	     10.00 	     11.00 	     -3.00 	) * (	X3) = (	     27.00)
(	      1.00 	      2.00 	      3.00 	      4.00 	) * (	X4) = (	     10.00)
Нормализуем строку с найденным элементом:
(	      1.00*	      1.08 	      1.15 	      1.23 	) * (	X1) = (	      4.46)
(	      5.00 	

TypeError: list indices must be integers or slices, not tuple

In [44]:
def gaussian(A,b):
    A = numpy.array(A) # Матрица (левая часть системы)
    b = numpy.array(b) # Вектор (правая часть системы)
    rezalt = numpy.linalg.solve(A, b)
    return rezalt

In [41]:
import numpy # импортируем библиотеку 

M4 = numpy.array([[1.,  2.,  3.,  4.,], [ 5.,  6., 88., -3.,], [ 9., 10., 11., -3.,], [13., 14., 15., 16.,]]) # Матрица (левая часть системы)
v4 = numpy.array([10., 96., 27., 58.,]) # Вектор (правая часть системы)

numpy.linalg.solve(M4, v4)

array([1., 1., 1., 1.])

In [43]:
A = [
    [1.,  2.,  3.,  4.,],
 [ 5.,  6., 88., -3.,],
 [ 9., 10., 11., -3.,],
 [13., 14., 15., 16.,],
 ]

b = [10., 96., 27., 58.,]
print (gaussian (A,b))

[1. 1. 1. 1.]


In [45]:
A = np.arange(1, 17, dtype=np.float64).reshape(4,4)
A[1,2] = 88
A[1,3] = -3
A[2,3] = -3
print(f'A = {A}')
x = np.ones(A.shape[0])
print(f'Original x = {x}')
b = A @ x.T
print(f'Right hand side for testing: b = {b}')
Ae = gaussian(A, b)
print(f'Check if A was unchanged ')
print(f'Eliminated augmented matrix:\n {Ae}')
print(f'Eliminated augmented matrix A part: {Ae[:,:-1]}')
print(f'Eliminated augmented matrix b part: {Ae[:,Ae.shape[1]-1]}')
# Find solution
x = back(Ae[:,:-1],Ae[:,Ae.shape[1]-1])
print(f'Solution: {x}')

A = [[ 1.  2.  3.  4.]
 [ 5.  6. 88. -3.]
 [ 9. 10. 11. -3.]
 [13. 14. 15. 16.]]
Original x = [1. 1. 1. 1.]
Right hand side for testing: b = [10. 96. 27. 58.]
Check if A was unchanged 
Eliminated augmented matrix:
 [1. 1. 1. 1.]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [40]:
def make_identity(matrix):
    matrix = ([ 1,  2,  3,  4.]
    [ 5,  6, 88, -3.]
    [ 9, 10, 11, -3.]
    [13, 14, 15, 16.])
    # перебор строк в обратном порядке 
    for nrow in range(len(matrix)-1,0,-1):
        row = matrix[nrow]
        for upper_row in matrix[:nrow]:
            factor = upper_row[nrow]
            upper_row -= factor*row
    return matrix

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\1B72~1\AppData\Local\Temp/ipykernel_5608/1517465407.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  matrix = ([ 1,  2,  3,  4.]
